config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    resources :customers, only:[:index, :show]
    patch '/customers/:id/ban' => 'customers#ban'
    patch '/customers/:id/unban' => 'customers#unban', as: 'unban'
    resources :reports, only:[:index, :show]
    resources :requests, only:[:index, :show]
    resources :tickets, except:[:new, :show]
  end


  devise_for :users, controllers: {
  	registrations: 'users/registrations',
  	sessions: 'users/sessions'
  }

  root 'home#top'
  get '/about' => 'home#about'

  namespace :users do
    patch '/customers/:id/withdraw' => 'customers#withdraw', as: 'withdraw'
  	resources :customers, except:[:new, :create] do
      resources :reports, only:[:new, :create]
    end
  	resources :requests do
  		resources :participants, only:[:create, :destroy]
  	end
    resources :purchases, only:[:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participant.rb
class Participant < ApplicationRecord

	belongs_to :user
	belongs_to :request

	validates :user_id, presence: true
	validates :request_id, presence: true

end

app/models/purchase.rb
class Purchase < ApplicationRecord

	belongs_to :user
	belongs_to :ticket

	validates :payment_method, presence: true
	validates :charge, presence: true
	validates :quantity, presence: true
	validates :ticket_id, presence: true
	validates :user_id, presence: true

	enum payment_method: { クレジットカード: 0, 銀行振込: 1 }

end

app/models/purchased_ticket.rb
class PurchasedTicket < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord

	belongs_to :user

	validates :content, presence: true
	validates :respondent_id, presence: true

end

app/models/request.rb
class Request < ApplicationRecord

	belongs_to :user
	has_many :participants, dependent: :destroy

 	validates :datetime, presence: true
  	validates :address, presence: true
  	validates :title, presence: true
    validates :capacity, presence: true
    validates :deadline, presence: true
    validates :return_status, presence: true
    validates :user_id, presence: true

  	geocoded_by :address
  	after_validation :geocode, if: :address_changed?

  	attachment :image

  	def ticket_return(request)
      if request.return_status == 0
        if DateTime.now >= request.datetime
          request.user.update(ticket: request.user.ticket + request.capacity - request.participants.count)
          request.update(return_status: 1)
        end
      end
  	end

    def ticket_return_ban(request)
      if request.return_status == 0
        request.user.update(ticket: request.user.ticket + request.capacity)
        request.update(return_status: 1)
      end
    end

    def ticket_return_destroy(request)
      if request.return_status == 0
        request.user.update(ticket: request.user.ticket + request.capacity)
        request.update(return_status: 1)
        @participants = request.participants.all
        @participants.each do |participant|
          participant.user.update(ticket: participant.user.ticket - 1)
        end
      end
    end

end

app/models/ticket.rb
class Ticket < ApplicationRecord

	has_many :purchases

	validates :name, presence: true
	validates :price, presence: true
	validates :quantity, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :requests
  has_many :participants
  has_many :purchases
  has_many :reports

  validates :name, presence: true
  validates :age, presence: true
  validates :sex, presence: true
  validates :ticket, presence: true

  attachment :image

  enum sex: { 女性: 0, 男性: 1}

  include Discard::Model

end

app/controllers/admins/reports_controller.rb
class Admins::ReportsController < ApplicationController

	before_action :authenticate_admin!

	def index
		@reports = Report.page(params[:page]).per(10)
	end

	def show
		@report = Report.find(params[:id])
		@respondent = User.find(@report.respondent_id)
		@reports = Report.where(respondent_id: @report.respondent_id)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	def is_banned
		if current_user.is_banned == true
			redirect_to users_customer_path(current_user), flash: { error: "このアカウントは停止中のため一部の機能を利用できません。" }
		end
	end

	def any_requests_or_participants?(user)
	    @requests = user.requests.all
	    @req_in_progress = []
	    @participants = user.participants.all
	    @par_in_progress = []
	    @requests.each do |request|
	    	if request.datetime >= DateTime.now
	        	@req_in_progress.push(request)
	    	end
	    end
	    @participants.each do |participant|
	    	if participant.request.datetime >= DateTime.now
	        	@par_in_progress.push(participant)
	    	end
	    end
	end

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :age, :sex])
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def top
		
	end

	def about
		
	end
end

app/controllers/users/reports_controller.rb
class Users::ReportsController < ApplicationController

	before_action :authenticate_user!
	before_action :is_banned

	def new
		@report = Report.new
		@respondent = User.find(params[:customer_id])
	end

	def create
		@respondent = User.find(params[:customer_id])
		@report = Report.new(report_params)
		@report.user_id = current_user.id
		@report.respondent_id = @respondent.id
		if @report.save
			redirect_to users_customer_path(@respondent), flash: { notice: "#{@respondent.name}さんを通報しました。" }
		else
			render :new
		end
	end

	private

	def report_params
		params.require(:report).permit(:respondent_id, :content)
	end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/reports_helper.rb
module Admins::ReportsHelper
end

app/helpers/admins/requests_helper.rb
module Admins::RequestsHelper
end

app/helpers/admins/tickets_helper.rb
module Admins::TicketsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users/customers_helper.rb
module Users::CustomersHelper
end

app/helpers/users/participants_helper.rb
module Users::ParticipantsHelper
end

app/helpers/users/purchases_helper.rb
module Users::PurchasesHelper
end

app/helpers/users/reports_helper.rb
module Users::ReportsHelper
end

app/helpers/users/requests_helper.rb
module Users::RequestsHelper
end

app/views/admins/reports/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<table class="table table-bordered table-title">
				<thead>
					<tr>
						<th>通報一覧</th>
					</tr>
				</thead>
			</table>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>ID</th>
						<th>通報者</th>
						<th>通報相手</th>
						<th>通報日時</th>
					</tr>
				</thead>
				<tbody>
					<% @reports.each do |report| %>
						<tr>
							<td><%= link_to report.id, admins_report_path(report) %></td>
							<td><%= link_to report.user.id, admins_customer_path(report.user) %></td>
							<td>
								<%= link_to User.find(report.respondent_id).id, admins_customer_path(report.respondent_id) %>
								</td>
							<td><%= report.created_at %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
	<%= paginate @reports %>
</div>

app/views/admins/reports/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<table class="table table-bordered">
				<tbody>
					<tr>
						<th>通報者</th>
						<td><%= link_to @report.user.name, admins_customer_path(@report.user) %></td>
					</tr>
					<tr>
						<th>通報相手</th>
						<td><%= link_to @respondent.name, admins_customer_path(@respondent) %></td>
					</tr>
					<tr>
						<th>通報理由</th>
						<td><%= @report.content %></td>
					</tr>
					<tr>
						<th>通報日時</th>
						<td><%= @report.created_at %></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<table class="table table-bordered table-title">
				<thead>
					<tr>
						<th><%= @respondent.name %>さんへの通報一覧</th>
					</tr>
				</thead>
			</table>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>ID</th>
						<th>通報者</th>
						<th>通報日時</th>
					</tr>
				</thead>
				<tbody>
					<% @reports.each do |report| %>
						<tr>
							<td><%= link_to report.id, admins_report_path(report) %></td>
							<td><%= link_to report.user.id, admins_customer_path(report.user) %></td>
							<td><%= report.created_at %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>