config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    resources :customers, only:[:index, :show]
    patch '/customers/:id/ban' => 'customers#ban'
    patch '/customers/:id/unban' => 'customers#unban', as: 'unban'
    resources :reports, only:[:index, :show]
    resources :requests, only:[:index, :show]
    resources :tickets, except:[:new, :show]
  end


  devise_for :users, controllers: {
  	registrations: 'users/registrations',
  	sessions: 'users/sessions'
  }

  root 'home#top'
  get '/about' => 'home#about'

  namespace :users do
    patch '/customers/:id/withdraw' => 'customers#withdraw', as: 'withdraw'
  	resources :customers, except:[:new, :create] do
      resources :reports, only:[:new, :create]
    end
  	resources :requests do
  		resources :participants, only:[:create, :destroy]
  	end
    resources :purchases, only:[:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :requests
  has_many :participants
  has_many :purchases
  has_many :reports

  validates :name, presence: true
  validates :age, presence: true
  validates :sex, presence: true
  validates :ticket, presence: true

  attachment :image

  enum sex: { 女性: 0, 男性: 1}

  include Discard::Model

end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController

	before_action :authenticate_admin!

	def index
		@users = User.page(params[:page]).per(10)
	end

	def show
		@user = User.find(params[:id])
		@participants = @user.participants.page(params[:page]).per(5)
		@requests = @user.requests.page(params[:page]).per(5)
		@purchases = @user.purchases.page(params[:page]).per(5)
	end

	def ban
		@user = User.find(params[:id])
		any_requests_or_participants?(@user)
		if @req_in_progress.blank? == false
			@req_in_progress.each do |request|
				request.ticket_return_ban(request)
				request.destroy
			end
		end
		if @par_in_progress.blank? == false
			@par_in_progress.each do |participant|
				participant.user.update(ticket: participant.user.ticket - 1)
				participant.destroy
			end
		end
		@user.update(is_banned: true)
		redirect_to admins_customer_path(@user)
	end

	def unban
		@user = User.find(params[:id])
		@user.update(is_banned: false)
		redirect_to admins_customer_path(@user)
	end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/customers_controller.rb
class Users::CustomersController < ApplicationController

	before_action :authenticate_user!
	before_action :is_banned, only:[:edit, :update]

	def show
		@user = User.find(params[:id])
		@participants = @user.participants.page(params[:page]).per(5)
		@requests = @user.requests.page(params[:page]).per(5)
		@requests.each do |request|
			request.ticket_return(request)
		end
	end

	def edit
		@user = current_user
	end

	def update
		@user = current_user
		if @user.update(user_params)
			redirect_to users_customer_path(current_user)
		else
			render :edit
		end
	end

	def withdraw
		@user = current_user
		any_requests_or_participants?(@user)
		if @req_in_progress.blank? == false
	    	redirect_to users_customer_path(@user), flash: { error: "進行中の依頼があるため退会できません。" }
	    	return
	    elsif @par_in_progress.blank? == false
	    	redirect_to users_customer_path(@user), flash: { error: "進行中の助っ人があるため退会できません。" }
	    	return
	    else
		    @user.discard
			reset_session
			redirect_to '/'
	    end
	end

	private
	def user_params
		params.require(:user).permit(:name, :age, :sex, :image, :introduction)
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/participants_controller.rb
class Users::ParticipantsController < ApplicationController

	before_action :authenticate_user!
	before_action :is_banned

	def create
		@request = Request.find_by(id: params[:request_id])
		@participant = @request.participants.new
		@participant.user_id = current_user.id
		if @request.capacity > @request.participants.count
			if @participant.save
				current_user.update(ticket: current_user.ticket + 1)
			else
			end
		else
			redirect_to users_request_path(@request), flash: { error: "定員に達しています" }
		end
		redirect_to users_request_path(@request)
	end

	def destroy
		@participant = Participant.find_by(request_id: params[:request_id],
										   id: params[:id])
		if @participant.user.ticket >= 1
			@participant.destroy
			current_user.update(ticket: current_user.ticket - 1)
		else
			redirect_to users_request_path(@participant.request), flash: { error: "キャンセル用のチケットが不足しています" }
		end
		redirect_to users_request_path(@participant.request)
	end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/purchases_controller.rb
class Users::PurchasesController < ApplicationController

	before_action :authenticate_user!
	before_action :is_banned, only: :create

	def new
		@tickets = Ticket.all
		@purchase = Purchase.new
		@purchases = current_user.purchases.page(params[:page]).per(5)
	end

	def create
		if params[:purchase][:ticket_id] == "" || params[:purchase][:quantity] == ""
			redirect_to new_users_purchase_path, flash: { error: "購入内容を入力してください。" }
		else
			@user = current_user
			@purchase = @user.purchases.new(purchase_params)
			@ticket = Ticket.find_by(id: params[:purchase][:ticket_id])
			@purchase.charge = @ticket.price * params[:purchase][:quantity].to_i
			@user.update(ticket: @user.ticket + @ticket.quantity * params[:purchase][:quantity].to_i)
			if @purchase.save
				redirect_to users_customer_path(current_user), flash: { notice: "チケットが#{@ticket.quantity * params[:purchase][:quantity].to_i}枚追加されました。" }
			else
				render :new
			end
		end
	end

	private

	def purchase_params
		params.require(:purchase).permit(:ticket_id, :payment_method, :quantity)
	end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def after_sign_up_path_for(resource)
   users_customer_path(resource)
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/reports_controller.rb
class Users::ReportsController < ApplicationController

	before_action :authenticate_user!
	before_action :is_banned

	def new
		@report = Report.new
		@respondent = User.find(params[:customer_id])
	end

	def create
		@respondent = User.find(params[:customer_id])
		@report = Report.new(report_params)
		@report.user_id = current_user.id
		@report.respondent_id = @respondent.id
		if @report.save
			redirect_to users_customer_path(@respondent), flash: { notice: "#{@respondent.name}さんを通報しました。" }
		else
			render :new
		end
	end

	private

	def report_params
		params.require(:report).permit(:respondent_id, :content)
	end

end

app/controllers/users/requests_controller.rb
class Users::RequestsController < ApplicationController

	before_action :authenticate_user!, except: :index
	before_action :is_banned, except: [:index, :show]
	before_action :cannot_change, only: [:edit, :update, :destroy]

	def index
		@requests = Request.page(params[:page]).per(10)
	end

	def new
		@request = Request.new
	end

	def create
		@request = current_user.requests.new(request_params)
		if current_user.ticket >= params[:request][:capacity].to_i
			if @request.save
				current_user.update(ticket: current_user.ticket - params[:request][:capacity].to_i)
				redirect_to users_requests_path
			else
				render :new
			end
		else
			redirect_to new_users_request_path, flash: { error: "助っ人チケットが不足しています" }
		end
	end

	def show
		@request = Request.find(params[:id])
		@participants = @request.participants.all
		@participant = Participant.find_by(request_id: @request.id,
										   user_id: current_user.id)
	end

	def edit
	end

	def update
		difference = params[:request][:capacity].to_i - @request.capacity
		if current_user.ticket >= difference
			if @request.update(request_params)
				current_user.update(ticket: current_user.ticket - difference)
				redirect_to users_request_path(@request), flash: { notice: "依頼内容を更新しました。" }
			else
				render :edit
			end
		else
			redirect_to edit_users_request_path(@request), flash: { error: "チケットが不足しています。" }
		end
	end

	def destroy
		@request.ticket_return_destroy(@request)
		@request.destroy
		redirect_to users_customer_path(current_user), flash: { error: "依頼を削除し、募集人数分のチケットが返還されました。" }
	end

	private

	def request_params
		params.require(:request).permit(:datetime, :address, :title, :content, :capacity, :image, :deadline)
	end

	def cannot_change
		@request = Request.find(params[:id])
		if @request.user == current_user
			if DateTime.now >= @request.datetime
				redirect_to users_request_path(@request), flash: { error: "依頼が終了しているため変更できません。" }
			end
		else
			redirect_to users_request_path(@request), flash: { error: "依頼者以外は変更できません。" }
		end
	end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  before_action :reject_user, only: [:create]

  def after_sign_in_path_for(resource)
    users_customer_path(resource)
  end

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.discarded? == true))
        flash[:error] = "退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash[:error] = "メールアドレスまたはパスワードが違います。"
    end
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/users/customers_helper.rb
module Users::CustomersHelper
end

app/helpers/users/participants_helper.rb
module Users::ParticipantsHelper
end

app/helpers/users/purchases_helper.rb
module Users::PurchasesHelper
end

app/helpers/users/reports_helper.rb
module Users::ReportsHelper
end

app/helpers/users/requests_helper.rb
module Users::RequestsHelper
end

app/views/users/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <h1>EDIT USER</h1>
    </div>
  </div>
  <div class="row">
      <div class="col-sm-10 col-md-8 col-lg-6 offset-sm-1 offset-md-2 offset-lg-3">
        <%= render 'layouts/error_messages', model: @user %>
      </div>
  </div>
	<div class="row">
		<div class="col-sm-10 col-md-8 col-lg-6 offset-sm-1 offset-md-2 offset-lg-3 edit-user-form">
			<%= form_with model: @user, local: true, url: users_customer_path(@user) do |f| %>
			    <div class="form-group row">
			        <%= f.label :"*名前", class: "col-3 col-form-label" %>
			        <div class="col-9">
		            	<%= f.text_field :name, class: "form-control" %>
	            	</div>
			    </div>
        		<div class="form-group row">
          			<%= f.label :"*年齢", class: "col-3 col-form-label" %>
          			<div class="col-3">
            			<%= f.select :age, options_for_select((1..99).to_a), class: "form-control" %>
          			</div>
        		</div>
            <div class="form-group row">
              <%= f.label :"*性別", class: "col-3 col-form-label" %>
                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                  <label class="btn btn-outline-danger">
                    <%= f.radio_button :sex, "女性" %>女性
                  </label>
                  <label class="btn btn-outline-primary">
                    <%= f.radio_button :sex, "男性" %>男性
                  </label>
                </div>
            </div>
            <div class="form-group row">
              <%= f.label :"自己紹介文", class: "col-3 col-form-label" %>
              <div class="col-9">
                  <%= f.text_area :introduction, class: "form-control" %>
                </div>
            </div>
        		<div class="form-group row">
        			<%= f.label :"プロフィール画像", class: "col-3 col-form-label" %>
        			<div class="col-9">
        				<%= f.attachment_field :image %>
        			</div>
        		</div>
			    <div class="actions">
			        <%= f.submit "更新する", class: "btn btn-success", style: "width: 100%;" %>
			    </div>
			<% end %>
      <div class="caution">
        <p>*のついた項目は必ず入力してください。</p>
      </div>
      <hr class="my-4">
      <div class="caution">
        <p>退会を希望の方はこちら</p>
      </div>
      <%= link_to "退会する", users_withdraw_path(@user), class: "btn btn-outline-danger btn-sm", method: :patch, data: { confirm: "<i class='fa fa-exclamation-circle'></i>本当に退会しますか？",
                                cancel: "戻る",
                                commit: '退会する' } %>
		</div>
	</div>
</div>

app/views/users/customers/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1>USER</h1>
		</div>
	</div>
	<% if flash[:notice] %>
		<div class="row">
			<div class="col-sm-12 col-md-6 offset-md-3 notice-message">
				<%= flash[:notice] %>
			</div>
		</div>
	<% elsif flash[:error] %>
		<div class="row">
			<div class="col-sm-12 col-md-6 offset-md-3 error-message">
				<i class="fa fa-exclamation-circle"></i><%= flash[:error] %>
			</div>
		</div>
	<% end %>
	<div class="row no-gutters">
		<div class="col-8 offset-2 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-4 offset-lg-4 user">
			<div class="user-img">
				<%= attachment_image_tag @user, :image, format: 'jpeg', class: "img" %>
			</div>
			<div class="user-info">
				<p><%= @user.name %></p>
				<p>
					<% if @user.sex == "女性" %>
						<i class="fa fa-venus" style="color: red;"></i>
					<% else %>
						<i class="fa fa-mars" style="color: blue;"></i>
					<% end %>
					<%= @user.age %>才
				</p>
				<p><%= @user.introduction %></p>
			</div>
			<% if @user.id == current_user.id %>
				<%= link_to "編集する", edit_users_customer_path(@user), class: "btn btn-outline-success" %>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-8 col-md-6 offset-sm-2 offset-md-3">
			<input class="btn btn-primary" value="依頼履歴を表示" type="button" onclick="clickBtn1()" style="margin-top: 20px;"/>
			<input class="btn btn-primary" value="助っ人履歴を表示" type="button" onclick="clickBtn2()" style="margin-top: 20px;"/>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12 col-md-6 col-lg-5 offset-lg-1" id="user-table1">
			<table class="table table-bordered table-title">
				<thead>
					<tr>
						<th>依頼履歴</th>
					</tr>
				</thead>
			</table>
			<% if @requests.exists? %>
				<table class="table table-bordered">
					<tbody>
						<% @num = 1 %>
						<% @requests.each do |request| %>
							<tr>
								<th><%= @num %></th>
								<td><%= link_to request.title, users_request_path(request) %></td>
								<td><%= request.datetime.strftime('%Y/%m/%d') %></td>
								<td>
									<% if DateTime.now > request.datetime %>
										済
									<% else %>
										未
									<% end %>
								</td>
							</tr>
							<% @num = @num + 1 %>
						<% end %>
					</tbody>
				</table>
			<% else %>
				<table class="table table-bordered">
					<tbody>
						<tr>
							<td>依頼履歴はありません</td>
						</tr>
					</tbody>
				</table>
			<% end %>
			<%= paginate @requests %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-5" id="user-table2">
			<table class="table table-bordered table-title">
				<thead>
					<tr>
						<th>助っ人履歴</th>
					</tr>
				</thead>
			</table>
			<% if @participants.exists? %>
				<table class="table table-bordered">
					<tbody>
						<% @num = 1 %>
						<% @participants.each do |participant| %>
							<tr>
								<th><%= @num %></th>
								<td><%= link_to participant.request.title, users_request_path(participant.request) %></td>
								<td><%= participant.request.datetime.strftime('%Y/%m/%d') %></td>
								<td>
									<% if DateTime.now > participant.request.datetime %>
										済
									<% else %>
										未
									<% end %>
								</td>
							</tr>
							<% @num = @num + 1 %>
						<% end %>
					</tbody>
				</table>
			<% else %>
				<table class="table table-bordered">
					<tbody>
						<tr>
							<td>助っ人履歴はありません</td>
						</tr>
					</tbody>
				</table>
			<% end %>
			<%= paginate @participants %>
		</div>
	</div>
	<% if @user != current_user %>
		<div class="row">
			<div class="col-sm-8 col-md-6 offset-sm-2 offset-md-3">
				<%= link_to "通報する", new_users_customer_report_path(@user), class: "btn btn-outline-danger", style: "margin-top: 20px;" %>
			</div>
		</div>
	<% end %>
</div>

<script>
document.getElementById("user-table1").style.display = "none";
function clickBtn1(){
	const table1 = document.getElementById("user-table1");
	if (table1.style.display == "block"){
		table1.style.display = "none";
	} else {
		table1.style.display = "block";
	}
}
document.getElementById("user-table2").style.display = "none";
function clickBtn2(){
	const table2 = document.getElementById("user-table2");
	if (table2.style.display == "block"){
		table2.style.display = "none";
	} else {
		table2.style.display = "block";
	}
}
</script>