config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :admins do
    resources :customers, only:[:index, :show]
    patch '/customers/:id/ban' => 'customers#ban'
    patch '/customers/:id/unban' => 'customers#unban', as: 'unban'
    resources :reports, only:[:index, :show]
    resources :requests, only:[:index, :show]
    resources :tickets, except:[:new, :show]
  end


  devise_for :users, controllers: {
  	registrations: 'users/registrations',
  	sessions: 'users/sessions'
  }

  root 'home#top'
  get '/about' => 'home#about'

  namespace :users do
    patch '/customers/:id/withdraw' => 'customers#withdraw', as: 'withdraw'
  	resources :customers, except:[:new, :create] do
      resources :reports, only:[:new, :create]
    end
  	resources :requests do
  		resources :participants, only:[:create, :destroy]
  	end
    resources :purchases, only:[:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participant.rb
class Participant < ApplicationRecord

	belongs_to :user
	belongs_to :request

	validates :user_id, presence: true
	validates :request_id, presence: true

end

app/models/purchase.rb
class Purchase < ApplicationRecord

	belongs_to :user
	belongs_to :ticket

	validates :payment_method, presence: true
	validates :charge, presence: true
	validates :quantity, presence: true
	validates :ticket_id, presence: true
	validates :user_id, presence: true

	enum payment_method: { クレジットカード: 0, 銀行振込: 1 }

end

app/models/purchased_ticket.rb
class PurchasedTicket < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord

	belongs_to :user

	validates :content, presence: true
	validates :respondent_id, presence: true

end

app/models/request.rb
class Request < ApplicationRecord

	belongs_to :user
	has_many :participants, dependent: :destroy

 	validates :datetime, presence: true
  	validates :address, presence: true
  	validates :title, presence: true
    validates :capacity, presence: true
    validates :deadline, presence: true
    validates :return_status, presence: true
    validates :user_id, presence: true

  	geocoded_by :address
  	after_validation :geocode, if: :address_changed?

  	attachment :image

  	def ticket_return(request)
      if request.return_status == 0
        if DateTime.now >= request.datetime
          request.user.update(ticket: request.user.ticket + request.capacity - request.participants.count)
          request.update(return_status: 1)
        end
      end
  	end

    def ticket_return_ban(request)
      if request.return_status == 0
        request.user.update(ticket: request.user.ticket + request.capacity)
        request.update(return_status: 1)
      end
    end

    def ticket_return_destroy(request)
      if request.return_status == 0
        request.user.update(ticket: request.user.ticket + request.capacity)
        request.update(return_status: 1)
        @participants = request.participants.all
        @participants.each do |participant|
          participant.user.update(ticket: participant.user.ticket - 1)
        end
      end
    end

end

app/models/ticket.rb
class Ticket < ApplicationRecord

	has_many :purchases

	validates :name, presence: true
	validates :price, presence: true
	validates :quantity, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :requests
  has_many :participants
  has_many :purchases
  has_many :reports

  validates :name, presence: true
  validates :age, presence: true
  validates :sex, presence: true
  validates :ticket, presence: true

  attachment :image

  enum sex: { 女性: 0, 男性: 1}

  include Discard::Model

end

app/controllers/admins/tickets_controller.rb
class Admins::TicketsController < ApplicationController

	before_action :authenticate_admin!

	def index
		@tickets = Ticket.all
		@ticket = Ticket.new
	end

	def create
		@ticket = Ticket.new(ticket_params)
		if @ticket.save
			redirect_to admins_tickets_path
		else
			render :index
		end
	end

	def edit
		@ticket = Ticket.find(params[:id])
	end

	def update
		@ticket = Ticket.find(params[:id])
		if @ticket.update(ticket_params)
			redirect_to admins_tickets_path
		else
			render :index
		end
	end

	def destroy
		@ticket = Ticket.find(params[:id])
		@ticket.destroy
		redirect_to admins_tickets_path
	end

	private
	def ticket_params
		params.require(:ticket).permit(:name, :price, :quantity)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	def is_banned
		if current_user.is_banned == true
			redirect_to users_customer_path(current_user), flash: { error: "このアカウントは停止中のため一部の機能を利用できません。" }
		end
	end

	def any_requests_or_participants?(user)
	    @requests = user.requests.all
	    @req_in_progress = []
	    @participants = user.participants.all
	    @par_in_progress = []
	    @requests.each do |request|
	    	if request.datetime >= DateTime.now
	        	@req_in_progress.push(request)
	    	end
	    end
	    @participants.each do |participant|
	    	if participant.request.datetime >= DateTime.now
	        	@par_in_progress.push(participant)
	    	end
	    end
	end

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :age, :sex])
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def top
		
	end

	def about
		
	end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/reports_helper.rb
module Admins::ReportsHelper
end

app/helpers/admins/requests_helper.rb
module Admins::RequestsHelper
end

app/helpers/admins/tickets_helper.rb
module Admins::TicketsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users/customers_helper.rb
module Users::CustomersHelper
end

app/helpers/users/participants_helper.rb
module Users::ParticipantsHelper
end

app/helpers/users/purchases_helper.rb
module Users::PurchasesHelper
end

app/helpers/users/reports_helper.rb
module Users::ReportsHelper
end

app/helpers/users/requests_helper.rb
module Users::RequestsHelper
end

app/views/admins/tickets/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-12 col-md-8 offset-md-2 ticket-form">
			<%= form_with model: @ticket, url: admins_ticket_path(@ticket) do |f| %>
			    <div class="form-group row">
			        <%= f.label :"名前", class: "col-3 col-form-label" %>
			        <div class="col-6">
		            	<%= f.text_field :name, class: "form-control" %>
	            	</div>
			    </div>
			    <div class="form-group row">
			        <%= f.label :"枚数", class: "col-3 col-form-label" %>
			        <div class="col-1">
						<%= f.select :quantity, options_for_select((1..99).to_a), class: "form-control" %>
					</div>
					<%= f.label :"価格(円)", class: "col-3 col-form-label" %>
			        <div class="col-2">
		            	<%= f.text_field :price, class: "form-control" %>
	            	</div>
			    </div>
			    <div class="actions">
			        <%= f.submit "更新する", class: "btn btn-success" %>
			    </div>
			<% end %>
		</div>
	</div>
</div>

app/views/admins/tickets/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-12 col-md-8 offset-md-2 ticket-form">
			<%= form_with model: @ticket, local: true, url: admins_tickets_path do |f| %>
				<div class="form-group row">
			        <%= f.label :"チケット名", class: "col-3 col-form-label" %>
			        <div class="col-6">
		            	<%= f.text_field :name, class: "form-control" %>
	            	</div>
			    </div>
			    <div class="form-group row">
			        <%= f.label :"枚数", class: "col-3 col-form-label" %>
			        <div class="col-1">
						<%= f.select :quantity, options_for_select((1..99).to_a), class: "form-control" %>
					</div>
					<%= f.label :"価格(円)", class: "col-3 col-form-label" %>
			        <div class="col-2">
		            	<%= f.text_field :price, class: "form-control" %>
	            	</div>
			    </div>
			    <div class="actions">
			        <%= f.submit "登録する", class: "btn btn-primary" %>
			    </div>
			<% end %>
		</div>
	</div>
	<div class="row">
		<table class="col-12 col-md-8 offset-md-2 table table-bordered table-title">
			<thead>
				<tr>
					<th>チケット一覧</th>
				</tr>
			</thead>
		</table>
		<table class="col-12 col-md-8 offset-md-2 table table-bordered">
			<tbody>
				<% @tickets.each do |ticket| %>
					<tr>
						<td><%= ticket.id %></td>
						<td><%= ticket.name %></td>
						<td><%= ticket.quantity %>枚</td>
						<td><%= ticket.price %>円</td>
						<td><%= link_to "編集する", edit_admins_ticket_path(ticket), class: "btn btn-outline-success" %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>